name: Deploy

on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 18 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: prepare download image folder script
        run: chmod +x "./ParsingGFolder.sh"
        
      - name: download image folder
        run: ./ParsingGFolder.sh ${{ secrets.IMAGE_GFOLDER_ID }} ${{ secrets.IMAGE_LOCAL_PATH }}
        
      - name: download publications yaml
        run: curl -L -o ./content/publications.yaml "https://drive.google.com/uc?export=download&id=${{ secrets.PUBLICATIONS_DRIVE_ID }}"
        
      - name: download work-history yaml
        run: curl -L -o ./content/work-historyMod.yaml "https://drive.google.com/uc?export=download&id=${{ secrets.HISTORY_DRIVE_ID }}"
      
      - name: download projects yaml
        run: curl -L -o ./content/projectsMod.yaml "https://drive.google.com/uc?export=download&id=${{ secrets.PROJECT_DRIVE_ID }}"

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.3.2
        env:
          PERSONAL_TOKEN: ${{ secrets.WEB_GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
